### PR TITLE
Create question-template.md

### PR DESCRIPTION
**Pull request by pglevy**
addresses #61

Brianna, what do you think of this approach to providing more inline context for what to do with question content pages?

### CODE REVIEW

**Comment by pglevy** [comment]
Oy, I tagged the wrong @bnaolu in the original comment. :)

**Comment by pglevy** [comment]
Now that I'm thinking about it, if we like this question template approach, we should probably go back and set up the three questions this way. I think it will cause less confusion than having a separate, unused file just for documentation. But we can nail down the content here first.

**Comment by bnaolu** [comment]
> Now that I'm thinking about it, if we like this question template approach, we should probably go back and set up the three questions this way. I think it will cause less confusion than having a separate, unused file just for documentation. But we can nail down the content here first.

Agreed, @pglevy ! I see the advantages of having an unused file for documentation, but I think this is a good enough for now. Really like how this is looking! :)

**Comment by pglevy** [comment]
Check out the question files and let me know if you think we should keep the separate template file.

**Review by bnaolu — APPROVED** [review]

**Review by bnaolu — COMMENTED** [review]
I'm definitely favoring the inline context comments. I like the template but it's probably not too necessary to have since we have the inline comments.

**Pull request merged**
